### ISSUE TITLE
Determinization issues: Unequal arguments : non-functional FST

### ISSUE THREAD

**Issue by dmort27** [Garvys/rustfst#165]
When attempting to call `determinize` on some wFSTs, I get error messages like the following:
```
Unequal arguments : non-functional FST ? w1 = StringWeightRestrict { value: Labels([45, 62]) } w2 = StringWeightRestrict { value: Labels([45, 40]) }
```
As far as I can tell, this not very informative error message goes back to OpenFST, but even there, its meaning seems unclear. What could the problem be?

I haven't been able to reproduce this error with smaller FSTs, but I'll try.

**Comment by Garvys** [comment]
Hello ! 
Sorry for the late reply ! 
This error is raised because you are using a Non-Functional FST meaning giving one input sequence, your FST produces multiple different sequences. To be able to use the determinization with this kind of Fst, you must change the `det_type` when calling the `determinize` function and use `DeterminizeDisambiguate` for instance.
Hope this fixes your issue :-)
